apiVersion: v1
kind: Service        # Type of Kubernetes resource
metadata:
  name: {{  .Values.service.name | default (include "redis.fullname" .) }}
  labels:            # Labels that will be applied to this resource
    {{- include "redis.labels" . | nindent 4 }}    # Labels to be applied to this deployment
spec:
  {{- if eq .Values.service.headless true }}
  clusterIP: "None" # Headless service
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}       # Map incoming connections on port 6379 to the target port 6379 of the Pod
    targetPort: client
    name: tcp
  selector:          # Map any Pod with the specified labels to this service
{{- include "redis.selectorLabels" . | nindent 4 }}