apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "ecr-pull-secret.labels" . | nindent 4 }}
  name: post-install
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 2
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  suspend: false
  template:
    metadata:
      labels:
        {{- include "ecr-pull-secret.labels" . | nindent 8 }}
        job-name: post-install
    spec:
      automountServiceAccountToken: true
      containers:
      - command:
        - /bin/sh
        - -c
        - /scripts/run.sh
        envFrom:
        - secretRef:
            name: ecr-registry-helper
            optional: false
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        name: ecr-registry-helper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        {{- .Values.securityContext | toYaml | trim | nindent 8 }}
      serviceAccount: ecr-registry-helper
      serviceAccountName: ecr-registry-helper
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: visibility
        operator: Equal
        value: public
      volumes:
      - configMap:
          defaultMode: 0744
          name: ecr-scripts
        name: scripts
  ttlSecondsAfterFinished: 86400
