
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
automountServiceAccountToken: true
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-registry-helper
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
rules:
- apiGroups:
  - ""
  resourceNames:
  - av-ecr-private-registry
  resources:
  - secrets
  verbs:
  - delete
  - update
  - patch
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
{{- if .Values.podSecurityPolicy.enabled }}
- apiGroups:
  - ""
  resources:
    - podsecuritypolicy
  resourceNames:
    - ecr-pull-request
  verbs:
    - use
{{- end }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-registry-helper
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-registry-helper
subjects:
- kind: ServiceAccount
  name: ecr-registry-helper
---
