
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name }}
automountServiceAccountToken: true
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-registry-helper
rules:
- apiGroups:
  - ""
  resourceNames:
  - av-ecr-private-registry
  resources:
  - secrets
  verbs:
  - delete
  - update
  - patch
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
{{- if .Values.podSecurityPolicy.enabled }}
- apiGroups:
  - ""
  resources:
    - podsecuritypolicy
  resourceNames:
    - ecr-pull-request
  verbs:
    - use
{{- end }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-registry-helper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-registry-helper
subjects:
- kind: ServiceAccount
  name: ecr-registry-helper
---
