apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseCredentials.secret }}
  labels:
    {{- include "avx.labels" . | nindent 4 }}
data:
  host: {{ .Values.databaseCredentials.hostname | b64enc }}
  port: {{ .Values.databaseCredentials.port | toString | b64enc }}
  username: {{ .Values.databaseCredentials.username | b64enc }}
  password: {{ .Values.databaseCredentials.password | b64enc }}
  lockboxMasterKey: {{ include "avx.lockbox_master_key" . | required "This should not happen: blank output from 'avx.lockbox_master_key' template" | b64enc  }}
