apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseCredentials.secret }}
data:
  host: {{ .Values.databaseCredentials.hostname | b64enc }}
  port: {{ .Values.databaseCredentials.port | toString | b64enc }}
  username: {{ .Values.databaseCredentials.username | b64enc }}
  password: {{ .Values.databaseCredentials.password | b64enc }}
