{{- if .Values.imagePullSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.imagePullSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
# docker username, password, server is set to "username, password, docker.io"
# Will be overwritten from reflector
data:
  {{- if .Values.imagePullSecret.dockerconfigjson -}}
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
  {{- end -}}
{{- end -}}