apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseCredentials.secret }}
data:
  database:  {{ .Values.global.db.database | default "dbb_development" | b64enc}}
  host: {{ .Values.global.db.hostname | b64enc }}
  password: {{ .Values.global.db.password | b64enc }}
  port: {{ .Values.global.db.username | b64enc }}
  username: dbb-user
