apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "dbb.labels" . | nindent 4 }}
  name: dbb
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "dbb.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dbb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if not .Values.global.init }}
      initContainers:
      - name: dbb-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: ["bundle exec rails db:migrate"]
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/src/app/uploads/
          name: site-data
        env:
        - name: RAILS_ENV
          value: {{ .Values.global.environment }}
        - name: HOSTS
          value: "localhost,{{ include "dbb.hostname" . }}"
        - name: SKIP_TEST_DATABASE
          value: "true"
        - name: EA_SITE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: publicKey
              name: avx-site-public-key
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: LOCKBOX_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: lockboxMasterKey
              name: "{{ .Values.databaseCredentials.secret }}"
      {{- end }}
      containers:
      - name: dbb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: ["bundle exec rails s -b '0.0.0.0' -p {{ .Values.rails.port }}"]
        imagePullPolicy: Always
        ports:
          - name: http
            protocol: TCP
            containerPort: {{ .Values.rails.port }}
        {{- if not .Values.global.init }}
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          httpGet:
            path: /ping
            port: http
        {{- end }}
        volumeMounts:
        - mountPath: /usr/src/app/uploads/
          name: site-data
        env:
        - name: RAILS_ENV
          value: {{ .Values.global.environment }}
        - name: HOSTS
          value: "localhost,{{ include "dbb.hostname" . }}"
        - name: SKIP_TEST_DATABASE
          value: "true"
        - name: EA_SITE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: publicKey
              name: avx-site-public-key
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: LOCKBOX_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: lockboxMasterKey
              name: "{{ .Values.databaseCredentials.secret }}"
          # value: {{ .Values.lockboxMasterKey | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      - name: dbb-jobs
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: ["bundle exec rails jobs:work"]
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/src/app/uploads/
          name: site-data
        env:
        - name: RAILS_ENV
          value: {{ .Values.global.environment }}
        - name: HOSTS
          value: "localhost,{{ include "dbb.hostname" . }}"
        - name: SKIP_TEST_DATABASE
          value: "true"
        - name: EA_SITE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: publicKey
              name: avx-site-public-key
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: "{{ .Values.databaseCredentials.secret }}"
        - name: LOCKBOX_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: lockboxMasterKey
              name: "{{ .Values.databaseCredentials.secret }}"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 400Mi
      volumes:
      - name: site-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: dbb-data
        {{- else }}
        emptyDir:
          sizeLimit: {{ .Values.persistence.size }}
        {{- end }}