apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseCredentials.secret }}
  labels:
    {{- include "dbb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep" # lockboxMasterKey need to be kept
data:
  host: {{ .Values.databaseCredentials.hostname | b64enc }}
  database:  {{ .Values.databaseCredentials.database | b64enc}}
  port: {{ .Values.databaseCredentials.port | toString | b64enc }}
  username: {{ .Values.databaseCredentials.username | b64enc }}
  password: {{ .Values.databaseCredentials.password | b64enc }}
  lockboxMasterKey: {{ include "dbb.lockbox_master_key" . | required "This should not happen: blank output from 'dbb.lockbox_master_key' template" | b64enc  }}
