apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseCredentials.secret }}
  labels:
    {{- include "dbas.labels" . | nindent 4 }}
data:
  host: {{ .Values.databaseCredentials.hostname | b64enc }}
  database:  {{ .Values.databaseCredentials.database | b64enc}}
  port: {{ .Values.databaseCredentials.port | toString | b64enc }}
  username: {{ .Values.databaseCredentials.username | b64enc }}
  password: {{ .Values.databaseCredentials.password | b64enc }}
