service:
  name: ""
  port: 6379
  type: ClusterIP
  headless: true

image:
  tag: 7-alpine
  repository: redis
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi
