---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otp-sa
secrets:
- name: otp-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: otp-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otp
  name: otp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp
  strategy: {}
  template:
    metadata:
      labels:
        app: otp
    spec:
      serviceAccountName: otp-sa
      imagePullSecrets:
      - name: av-ecr-private-registry
      tolerations:
      - key: "visibility"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        k8s.assemblyvoting.net/pool: public
      initContainers:
      - image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/otp:latest
        name: otp-migrate
        command: ["/bin/sh", "-c"]
        args: ["bundle exec rails db:migrate"]
        imagePullPolicy: IfNotPresent
        env:
        - name: RAILS_ENV
          value: development
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: otp-development-database-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: otp-development-database-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: otp-development-database-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: otp-development-database-credentials
      containers:
      - name: otp
        image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/otp:latest
        command: ["/bin/sh", "-c"]
        args: ["sh -c \"bundle exec rails s -b '0.0.0.0' -p 3001\""]
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 3001
        env:
        - name: RAILS_ENV
          value: developments
        - name: LOCKBOX_MASTER_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000000"
        - name: SECRET_KEY_BASE
          value: "1"
        - name: MAILER_STRATEGY
          value: "smtp" # "smtp" | "aion_mailer" | "test"
        - name: SMTP_HOST
          value: "mailcatcher"
        - name: SMTP_PORT
          value: 1025
        - name: VA_SITE_PUBLIC_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000000"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: otp-development-database-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: otp-development-database-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: otp-development-database-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: otp-development-database-credentialss
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: otp
spec:
  selector:
    app: otp
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: otp.test-deployment.assemblyvoting.net
  name: otp
spec:
  ingressClassName: nginx
  rules:
  - host: otp.test-deployment.assemblyvoting.net
    http:
      paths:
      - backend:
          service:
            name: otp
            port:
              number: 3001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - otp.test-deployment.assemblyvoting.net
    secretName: otp-service