---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svs-sa
secrets:
- name: svs-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: svs-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svs
  name: svs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svs
  strategy: {}
  template:
    metadata:
      labels:
        app: svs
    spec:
      serviceAccountName: svs-sa
      imagePullSecrets:
      - name: av-ecr-private-registry
      tolerations:
      - key: "visibility"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        k8s.assemblyvoting.net/pool: public
      containers:
      - name: svs-api
        image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/svs-api:latest
        command: ["/bin/docker-entrypoint"]
        args: ["bundle exec rails s -b '0.0.0.0'"]
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 3020
        env:
        - name: RAILS_ENV
          value: development
        - name: PORT
          value: 3020
        - name: REDIS_URL
          value: "redis://svs-redis:6382"
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      - name: svs-client
        image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/svs-client:latest
        command: ["/bin/docker-entrypoint"]
        args: ["npm run dev:docker"]
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 8002
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      - name: redis
        image: redis:7
        args: ["--port", "6382"]
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svs-api
spec:
  selector:
    app: svs
  ports:
  - name: http
    port: 3020
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: svs-api.test-deployment.assemblyvoting.net
  name: svs-api
spec:
  ingressClassName: nginx
  rules:
  - host: svs-api.test-deployment.assemblyvoting.net
    http:
      paths:
      - backend:
          service:
            name: svs-api
            port:
              number: 3020
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - svs-api.test-deployment.assemblyvoting.net
    secretName: svs-api-service
---
apiVersion: v1
kind: Service
metadata:
  name: svs-client
spec:
  selector:
    app: svs
  ports:
  - name: http
    port: 8002
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-production
#     external-dns.alpha.kubernetes.io/hostname: svs-client.test-deployment.assemblyvoting.net
#   name: svs-client
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: svs-client.test-deployment.assemblyvoting.net
#     http:
#       paths:
#       - backend:
#           service:
#             name: svs-client
#             port:
#               number: 3012
#         path: /
#         pathType: Prefix
#   tls:
#   - hosts:
#     - svs-client.test-deployment.assemblyvoting.net
#     secretName: svs-client-service