---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcs-sa
secrets:
- name: tcs-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: tcs-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tcs
  name: tcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcs
  strategy: {}
  template:
    metadata:
      labels:
        app: tcs
    spec:
      serviceAccountName: tcs-sa
      imagePullSecrets:
      - name: av-ecr-private-registry
      tolerations:
      - key: "visibility"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        k8s.assemblyvoting.net/pool: public
      containers:
      - name: tcs-api
        image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/tcs-api:latest
        command: ["/bin/docker-entrypoint"]
        args: ["bundle exec rails s -b '0.0.0.0' -p 3007"]
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 3007
        env:
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: "redis://tcs-redis:6382"
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      - name: tcs-client
        image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/tcs-client:latest
        command: ["/bin/sh", "-c"]
        args: ["npm run dev -- --host 0.0.0.0 --port 3006"]
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 3006
        env:
        - name: VITE_TCS_URL
          value: "https://tcs-api.test-deployment.assemblyvoting.net"
        - name: VITE_ELECTION_SLUG
          value: SLUGGOESHERE
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      - name: redis
        image: redis:7
        args: ["--port", "6382"]
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tcs-api
spec:
  selector:
    app: tcs
  ports:
  - name: http
    port: 3000
    targetPort: 3007
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-production
#     external-dns.alpha.kubernetes.io/hostname: tcs-api.test-deployment.assemblyvoting.net
#   name: tcs-api
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: tcs-api.test-deployment.assemblyvoting.net
#     http:
#       paths:
#       - backend:
#           service:
#             name: tcs-api
#             port:
#               number: 3007
#         path: /
#         pathType: Prefix
#   tls:
#   - hosts:
#     - tcs-api.test-deployment.assemblyvoting.net
#     secretName: tcs-api-service