---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbas-sa
  namespace: "{{ .Release.Name }}"
secrets:
- name: dbas-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: dbas-sa
  namespace: "{{ .Release.Name }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbas
  name: dbas
  namespace: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbas
  strategy: {}
  template:
    metadata:
      labels:
        app: dbas
    spec:
      serviceAccountName: dbas-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: dbas
        image: "{{ .Values.dbb.image.repository }}:{{ .Values.dbb.image.tag }}"
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 3010
        env:
        - name: REACT_APP_BASE_ELECTION_URL
          value: "https://dbb.avx.{{ .Release.Name }}.assemblyvoting.net"
        - name: REACT_APP_STRICT
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 200m
            memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dbas
  namespace: "{{ .Release.Name }}"
spec:
  selector:
    app: dbas
  ports:
  - name: http
    port: 3010
    protocol: TCP
    targetPort: 3010
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.certificateIssuer }}"
    external-dns.alpha.kubernetes.io/hostname: "dbas.avx.{{ .Release.Name }}.assemblyvoting.net"
  name: dbas
  namespace: "{{ .Release.Name }}"
spec:
  ingressClassName: nginx
  rules:
  - host: "dbas.avx.{{ .Release.Name }}.assemblyvoting.net"
    http:
      paths:
      - backend:
          service:
            name: dbas
            port:
              number: 3010
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "dbas.avx.{{ .Release.Name }}.assemblyvoting.net"
    secretName: dbas-service
