---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: va-sa
  namespace: "{{ .Release.Name }}"
secrets:
- name: va-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: va-sa
  namespace: "{{ .Release.Name }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: va
  name: va
  namespace: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: va
  strategy: {}
  template:
    metadata:
      labels:
        app: va
    spec:
      serviceAccountName: va-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - key: "visibility"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        k8s.assemblyvoting.net/pool: public
      initContainers:
      - image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/va:latest
        name: va-migrate
        command: ["/bin/sh", "-c"]
        args: ["bundle exec rails db:migrate"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /usr/src/app/uploads/
          name: uploads
        env:
        - name: RAILS_ENV
          value: development
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: va-development-database-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: va-development-database-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: va-development-database-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: va-development-database-credentialss
      containers:
      - name: va
        image: 534003348933.dkr.ecr.eu-west-1.amazonaws.com/va:latest
        command: ["/bin/sh", "-c"]
        args: ["sh -c \"bundle exec rails s -b '0.0.0.0' -p 3002\""]
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 3002
        env:
        - name: RAILS_ENV
          value: development
        - name: HOSTS
          value: "localhost,va.test-deployment.assemblyvoting.net"
        - name: AVX_SITE_PUBLIC_KEY
          value: "00000000000000000000000000000000"
        - name: VA_SITE_PRIVATE_KEY
          value: "00000000000000000000000000000000"
        - name: VOTER_REGISTRY_ENDPOINT
          value: https://wdgxz5zqf7.execute-api.us-east-1.amazonaws.com/development-v3-1-2/lookupVoterEmail
        - name: VOTER_REGISTRY_API_KEY
          value: "00000000000000000000000000000000"
        - name: OTP_PROVIDER_HOST
          value: "otp:3001"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: va-development-database-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: va-development-database-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: va-development-database-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: va-development-database-credentials
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: va
spec:
  selector:
    app: va
  ports:
  - name: http
    port: 3002
    protocol: TCP
    targetPort: 3002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: va.test-deployment.assemblyvoting.net
  name: va
spec:
  ingressClassName: nginx
  rules:
  - host: va.test-deployment.assemblyvoting.net
    http:
      paths:
      - backend:
          service:
            name: va
            port:
              number: 3003
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - va.test-deployment.assemblyvoting.net
    secretName: va-service