apiVersion: v1
kind: Secret
metadata:
  name: exoscale-api-credentials
  labels:
    {{- include "exoscale-dbass-filter.labels" . | nindent 4 }}
#   annotations:
#     "helm.sh/resource-policy": keep
data:
  api-key:  {{ .Values.api.key | default .Values.global.exoscale.api.key | b64enc}}
  api-secret: {{ .Values.api.secret | default .Values.global.exoscale.api.secret | b64enc }}
  database-name: {{ .Values.database.name | default .Values.global.exoscale.database.name | b64enc }}
  database-zone: {{ .Values.database.zone | default .Values.global.exoscale.database.zone| b64enc }}
