apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exoscale-dbass-filter.serviceAccountName" . }}
  labels:
    {{- include "exoscale-dbass-filter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
